### ISSUE TITLE
How did you generate the non-rigid transformation?

### ISSUE THREAD

**Issue by wzm2256** [ohirose/bcpd#14]
Hi, thanks for sharing your code.

I have a question regarding the experiments. As you mentioned in Sec 5.1.  ''For each shape, we created the corresponding deformed shape using a non-rigid deformation tool.'' I'm wondering what is that tool?

Thanks again for your code.

**Comment by ohirose** [comment]
Hi, thank you for your interest in BCPD! I created the tool. Please read Sec. 3.5.2 in [the second paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9290402). I detailed how I created the dataset there.

**Comment by wzm2256** [comment]
Thanks, that is clear.

By the way, I have another question if it does not bother you too much.
It seems that the transformed point cloud is very small in the beginning of the registration process.  This is a little strange to me because the initial point clouds are about the same size. 
I guess it is just a result of the early steps of the registration algorithm, and it has nothing to do with the initialization step, am I right?

**Comment by ohirose** [comment]
I guess this phenomenon originates from both algorithm and initialization. 

The small deformed shape \hat{y} at the optimization beginning is due to **the randomness of the matching probability matrix P**. The almost random P produces \hat{x} concentrating on a source shape's mean point. Then, the small \hat{x} leads to a small deformed shape \hat{y} because the method finds \hat{y} minimizing the difference between \hat{x} and \hat{y}.

The randomness of P originates from the algorithm and initialization:
- As \gamma is larger, P becomes more random and produces a small \hat{y}.
- If \gamma is small and initial registration is poor, P also becomes random and produces a small \hat{y}.
- If \gamma is small and initial registration is good, P becomes non-random, leading to \hat{y} whose size is almost the same as a target shape.

**Comment by wzm2256** [comment]
Thanks for your helpful answer, I really appreciate that.
