### ISSUE TITLE
no output file

### ISSUE THREAD

**Issue by KIC-Crack** [ohirose/bcpd#19]
This is my terminal output, but no txt file is generated
`D:\Download\bcpd-master\win>bcpd.exe -x target.txt -y source.txt -w0.1 -o Output

  BCPD version 0.85 (2020/10/19). OpenMP: Turned on.

  Input Data:
    Point set 1 (target): [target.txt]
    Point set 2 (source): [source.txt]
    Size of point set 1:  [24230, 1]
    Size of point set 2:  [23410, 1]

  Parameters:
    omega   =  0.10
    lambda  =  2.00  --> the expected drift length = 0.707
    gamma   =  1.00
    kappa   =  inf

  Kernel:
    [Gaussian] with beta = 2.00

  Acceleration:
    Fast G:  OFF
    Fast P:  OFF

  Convergence:
    tolerance   =  1.0e-004
    max #loops  =  500
    min #loops  =  30

  Output:
    [Output*.txt]; * = y`

**Comment by ohirose** [comment]
Hi, there might be the following problems:

- Your input files are not tab-separated
  - Please see [issue#2](https://github.com/ohirose/bcpd/issues/2)
- You didn't activate any acceleration technique; bcpd failed because of the memory allocation error.
  - Please add the option `-A`; read [here](https://github.com/ohirose/bcpd#acceleration) carefully.
