### ISSUE TITLE
The volume of the minimum bounding box that covers the target point set X

### ISSUE THREAD

**Issue by Sunzhiliang** [ohirose/bcpd#6]
If "xn" is in the minimum bounding box ,**p**out("xn") = 1/V .However, I have difficulty understanding pout("xn") = 0.
When does the value of  **p**out("xn") = 0? Doesn't the minimum bounding box cover all target points? 
Thanks a lot in advance!

**Comment by ohirose** [comment]
Thank you for your interest. Actually, no input point that satisfies ![zero](https://user-images.githubusercontent.com/7005476/102150760-aba9cf00-3eb4-11eb-84b7-d36213d235f8.png) because all target points are inside the bounding box that covers the target point set. The condition ![math](https://user-images.githubusercontent.com/7005476/102151043-45717c00-3eb5-11eb-9bba-4d3a3d7ccf8e.png) outside the bounding box is required for the normalization condition of a probabilistic density function, i.e., ![norm](https://user-images.githubusercontent.com/7005476/102150590-47870b00-3eb4-11eb-8411-af975c916a46.png). The following page might be useful for your question: https://en.wikipedia.org/wiki/Continuous_uniform_distribution
